### PR TITLE
feat: text and private editor

### PR DESCRIPTION
**Pull request by jarradraumati**
This pull request implements `Text` nodes within other Nodes within the `Substation` section. They can then be deleted and edited (provided the Text wizard is available).

I'm unsure whether the rendering is what we might expect (a big box with the content).
Perhaps there might be a more elegant way of showing that a Node has a `Text` element contained within it.

image

Here is an example ssd file to play around with:

[XAT.zip](https://github.com/OpenEnergyTools/scl-substation-editor/files/13839489/XAT.zip)

I struggled to get the test screenshots to render the same on my machine (WSL2: Ubuntu 22.04 LTS).
I'm not too sure why they are slightly different. It might be prudent to re-render them.

It's not a priority to implement, but I'd be happy to discuss whether this feature fits into the editor.

### CODE REVIEW

**Comment by JakobVogelsang** [comment]
Hi @jarradraumati. First, thank you very much for this work!!! 

The screenshot testing is run on a macOS machine at the moment and I would update them at the ended for your convenience. I had a very brief look at the current PR and have one remark already for you: 
 
1. With this plugin we are aiming to filter out everything that is not used my a general user. This does belong to it in my opinion. This means I would love to have a filter button with an icon of your choice next to the filter functions in the right upper corner. I would propose to have an `abbr` on the button saying `Filter user-defined information`.
2. I would love you to show private sections as well showing the `type` of the `Private` element as well and filter on the same button. 

The second one would be nice to have  though :).

I shall look a bit further how well it works on tablets and smartphones and my have a bit more bickering :D.

**Comment by jarradraumati** [comment]
Thanks for the feedback @JakobVogelsang.

> 1. With this plugin we are aiming to filter out everything that is not used my a general user. This does belong to it in my opinion. This means I would love to have a filter button with an icon of your choice next to the filter functions in the right upper corner. I would propose to have an `abbr` on the button saying `Filter user-defined information`.

I've implemented the filter button. It will be disabled/hidden when functions are not visible.

> 2. I would love you to show private sections as well showing the `type` of the `Private` element as well and filter on the same button.
> 
> The second one would be nice to have though :).

Done. Via [5c1b894](https://github.com/OpenEnergyTools/scl-substation-editor/pull/4/commits/5c1b894b0836ea2a72186897741e1d63e519bbe0)

image

I've left the `Text` and `Private` elements as first render above other elements (e.g `LNodes`) since the filter button can easily hide them.

I think `Text` and `Private` under `LNode` should be handled differently. Not 100% sure how that might work. It's the only element I haven't implemented anything for yet.

**Comment by JakobVogelsang** [comment]
Hi @jarradraumati. Thank you very much again. I have tried it out now and am very happy! It works well with the other editors. I have one additional change request:
1. I would not have the tag name `Private` or `Text` in the title. You can distinguish them by the missing type of the `Text` element. 
2. I would show the whole content as a div within the element. That is exactly what I want to see there right? Right now I wonder what the additional elements are for if not to see the content right away.

**Comment by jarradraumati** [comment]
@JakobVogelsang I agree. Having the `Private` or `Text` tags in the label doesn't add much. They are distinguishable by the icon as well.

Regarding your second point, `Text` elements are very straightforward since they only contain text content. A div element with some styling to show newlines seems sensible:

image

`Private` elements are a bit different since they can contain children nodes or text content. Some of the children of private elements can contain nodes which only have text content too.

Simple private element examples are just text content (like these ones at the `SCL` level:

image

More complex `Private` elements have an entire structure beneath it. This is just the `InnerHTML` rendered for an `IEC 61850-6-100` private element:

image

We're able to limit the pane size and either style an overflow to cut it off, or add a scrollbar. I'm not entirely sure what the right approach might be.

Some experimental work specifically for `IEC 61850-6-100` shows that known private element structures could be rendered as action panes (not in the scope of this PR):

image

I'd appreciate your thoughts on what the content within the `div` might look like for different private element implementations.

**Comment by JakobVogelsang** [comment]
Most `Private` sections are one-liners and I think everything above need to be hidden. I therefore liked your idea on showing parts of the content only to the user. I think we could also add a `show more` type of thing where the user can choose to unfold to the complete content. I also would propose to pretty print private section content. 

What would you think about that?

**Comment by jarradraumati** [comment]
I have done some experimenting.
If we're keen to show the content within a private, I think a collapsible div works ok.
The CSS could be tidied up (I hacked this a bit without too much regard https://www.digitalocean.com/community/tutorials/css-collapsible).
But it does the job of being able to allow the user to see the content, and hide it when appropriate.

The label is just the beginning of the private element content, but it can be whatever you like it to be (I did have `Content` as the label at one point).

The pretty print took me a while to get my head around.
But it more or less looks like what is in the SCL file.

image

**Comment by JakobVogelsang** [comment]
Hi @jarradraumati thank you again for this great work. Your screenshot looks very fine. With me is is a bit different.

grafik

The text content in the header and in the first line are duplicate. I understant you did it to see as much of the content as possible. My gut feeling is it won't work. I feel that it is either a short one liner or you have to unfold to see the content anyway. 

Mybe we should work with the edit wizard after all and just make the two panes be limited in size and height? Or is it so important to see all private sections complete in the substation editor.

**Comment by jarradraumati** [comment]
@JakobVogelsang I feel that providing minimal information is better than showing everything. That seems more in line with other elements within the substation editor. If you want to see more information, then you use the edit wizard.

Complex private elements like those under IEC61850-6-100 probably deserve their own editor, rather than trying to mix it in with the substation editor. 

I'll tidy up this PR and keep it minimal with no duplication of content. There's some experimental work on the editors/wizards at https://jarradraumati.github.io/scl-editor/ if you're interested.

image

image

image

image

**Review by JakobVogelsang — APPROVED** [review]
Looks very good to me. Thank you very much for your contribution!!!!

**Pull request merged**
